In [56]:
import numpy as np
import pandas as pd

In [57]:
mybmidata = pd.read_csv(r"C:\ProgramData\Ml_Data\Bmi_male_female.csv")

In [58]:
mybmidata.head()

Gender  Height  Weight  Index
0    Male     174      96      4
1    Male     189      87      2
2  Female     185     110      4
3  Female     195     104      3
4    Male     149      61      3

In [59]:
mybmidata.tail()

Gender  Height  Weight  Index
495  Female     150     153      5
496  Female     184     121      4
497  Female     141     136      5
498    Male     150      95      5
499    Male     173     131      5

In [60]:
mybmidata.head(1)

Gender  Height  Weight  Index
0   Male     174      96      4

In [61]:
mybmidata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
Gender    500 non-null object
Height    500 non-null int64
Weight    500 non-null int64
Index     500 non-null int64
dtypes: int64(3), object(1)
memory usage: 15.7+ KB


In [62]:
#Index
#0 - Extremely Weak
#1 - Weak
#2 - Normal
#3 - Overweight
#4 - Obesity
#5 - Extreme Obesity

In [63]:
mybmidata['Gender']=="Male" #Comparision operator

0       True
1       True
2      False
3      False
4       True
5       True
6       True
7       True
8       True
9      False
10      True
11     False
12     False
13      True
14      True
15     False
16     False
17      True
18      True
19      True
20      True
21     False
22     False
23      True
24     False
25     False
26      True
27      True
28     False
29      True
       ...  
470     True
471     True
472    False
473     True
474    False
475     True
476    False
477     True
478    False
479    False
480    False
481    False
482    False
483     True
484    False
485     True
486    False
487     True
488     True
489    False
490    False
491    False
492    False
493    False
494     True
495    False
496    False
497    False
498     True
499     True
Name: Gender, dtype: bool

In [64]:
mybmidata[mybmidata['Gender']=="Male"]

Gender  Height  Weight  Index
0     Male     174      96      4
1     Male     189      87      2
4     Male     149      61      3
5     Male     189     104      3
6     Male     147      92      5
7     Male     154     111      5
8     Male     174      90      3
10    Male     195      81      2
13    Male     155      51      2
14    Male     191      79      2
17    Male     140     129      5
18    Male     144     145      5
19    Male     172     139      5
20    Male     157     110      5
23    Male     185     139      5
26    Male     190      95      3
27    Male     187      62      1
29    Male     179     152      5
30    Male     153     121      5
31    Male     178      52      1
37    Male     144      80      4
42    Male     157      56      2
43    Male     161     118      5
45    Male     185      76      2
47    Male     181     111      4
48    Male     161      72      3
49    Male     140     152      5
52    Male     163     110      5
53    Male     172     105      4
54    Male     196     116      4
..     ...     ...     ...    ...
438   Male     188      65      1
441   Male     182      73      2
442   Male     143     149      5
443   Male     152     146      5
445   Male     159     140      5
446   Male     146      70      4
449   Male     159     145      5
450   Male     162     157      5
453   Male     182      50      0
455   Male     176      77      2
458   Male     154      81      4
460   Male     179     123      4
461   Male     152     132      5
462   Male     179      56      1
465   Male     158     127      5
467   Male     145     142      5
468   Male     161     115      5
469   Male     198     109      3
470   Male     147     142      5
471   Male     154     112      5
473   Male     195     153      5
475   Male     183     131      4
477   Male     167      64      2
483   Male     146      85      4
485   Male     173     111      4
487   Male     187      80      2
488   Male     198     136      4
494   Male     152      98      5
498   Male     150      95      5
499   Male     173     131      5

[245 rows x 4 columns]

In [65]:
xx=mybmidata[mybmidata['Gender']=="Male"]

In [66]:
xx.shape

(245, 4)

In [67]:
len(mybmidata[mybmidata['Gender']=="Male"]) #OR len(xx) gives the same result

245

In [68]:
xx.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 245 entries, 0 to 499
Data columns (total 4 columns):
Gender    245 non-null object
Height    245 non-null int64
Weight    245 non-null int64
Index     245 non-null int64
dtypes: int64(3), object(1)
memory usage: 9.6+ KB


In [69]:
# next is additional

In [70]:
a = len(xx[xx["Index"]==0])

In [71]:
b = len(xx[xx["Index"]==1])

In [72]:
c= len(xx[xx["Index"]==2])

In [73]:
d= len(xx[xx["Index"]==3])

In [74]:
e= len(xx[xx["Index"]==4])

In [75]:
f = len(xx[xx["Index"]==5])

In [76]:
a+b+c+d+e+f

245

In [77]:
#NOW,

In [78]:
mybmidata.iloc[:,0:3]

Gender  Height  Weight
0      Male     174      96
1      Male     189      87
2    Female     185     110
3    Female     195     104
4      Male     149      61
5      Male     189     104
6      Male     147      92
7      Male     154     111
8      Male     174      90
9    Female     169     103
10     Male     195      81
11   Female     159      80
12   Female     192     101
13     Male     155      51
14     Male     191      79
15   Female     153     107
16   Female     157     110
17     Male     140     129
18     Male     144     145
19     Male     172     139
20     Male     157     110
21   Female     153     149
22   Female     169      97
23     Male     185     139
24   Female     172      67
25   Female     151      64
26     Male     190      95
27     Male     187      62
28   Female     163     159
29     Male     179     152
..      ...     ...     ...
470    Male     147     142
471    Male     154     112
472  Female     178      65
473    Male     195     153
474  Female     167      79
475    Male     183     131
476  Female     164     142
477    Male     167      64
478  Female     151      55
479  Female     147     107
480  Female     155     115
481  Female     172     108
482  Female     142      86
483    Male     146      85
484  Female     188     115
485    Male     173     111
486  Female     160     109
487    Male     187      80
488    Male     198     136
489  Female     179     150
490  Female     164      59
491  Female     146     147
492  Female     198      50
493  Female     170      53
494    Male     152      98
495  Female     150     153
496  Female     184     121
497  Female     141     136
498    Male     150      95
499    Male     173     131

[500 rows x 3 columns]

In [79]:
x_bmi = mybmidata.iloc[:,0:3]

In [80]:
x_bmi.head()

Gender  Height  Weight
0    Male     174      96
1    Male     189      87
2  Female     185     110
3  Female     195     104
4    Male     149      61

In [107]:
#  x_bmi[x_bmi["Gender"]=="Male"]==0
#  x_bmi[x_bmi["Gender"]=="Female"]==1

In [82]:
#Using mapping and disctionary
x_bmi["Gender"] = x_bmi["Gender"].map({"Male":0,"Female":1})

In [83]:
x_bmi.head()

Gender  Height  Weight
0       0     174      96
1       0     189      87
2       1     185     110
3       1     195     104
4       0     149      61

In [84]:
y_target = mybmidata["Index"]

In [85]:
type(y_target)

pandas.core.series.Series

In [86]:
y_target.head()

0    4
1    2
2    4
3    3
4    3
Name: Index, dtype: int64

In [87]:
index_name = pd.Series(["Extremely Weak","Weak","Normal","Overweight","Obesity","Extreme Obesity"])

In [88]:
index_name

0     Extremely Weak
1               Weak
2             Normal
3         Overweight
4            Obesity
5    Extreme Obesity
dtype: object

In [89]:
print(f"type of x_bmi {type(x_bmi)} and type of y_target {type(y_target)}")

type of x_bmi <class 'pandas.core.frame.DataFrame'> and type of y_target <class 'pandas.core.series.Series'>


In [90]:
X_input = x_bmi.values
Y_target = y_target.values   
#Conversion

In [91]:
print(f"type of x_bmi {type(X_input)} and type of y_target {type(Y_target)}")

type of x_bmi <class 'numpy.ndarray'> and type of y_target <class 'numpy.ndarray'>


In [92]:
print(X_input)

[[  0 174  96]
 [  0 189  87]
 [  1 185 110]
 ..., 
 [  1 141 136]
 [  0 150  95]
 [  0 173 131]]


In [93]:
print(Y_target)

[4 2 4 3 3 3 5 5 3 4 2 4 3 2 2 5 5 5 5 5 5 5 4 5 2 3 3 1 5 5 5 1 1 5 5 4 3
 4 5 2 4 5 2 5 4 2 4 4 3 5 5 1 5 4 4 3 4 5 3 5 0 5 0 2 5 5 4 2 4 4 2 4 5 2
 3 4 4 4 4 0 3 5 3 4 5 0 5 5 5 5 5 3 3 2 4 5 4 5 1 0 4 5 5 4 4 4 5 5 4 3 4
 5 4 2 4 3 2 5 5 5 4 4 4 5 5 4 4 4 5 2 5 2 5 4 5 5 5 3 5 5 2 4 5 5 5 4 3 5
 3 3 0 3 3 5 5 4 3 5 3 4 2 2 3 5 4 2 4 5 3 2 4 5 5 4 4 4 4 3 5 3 3 4 4 2 3
 3 5 3 5 4 5 5 4 5 5 5 4 4 5 5 1 3 4 4 5 4 5 4 3 4 4 5 5 5 0 5 5 5 5 5 2 5
 4 5 0 5 3 4 5 5 4 2 3 3 4 3 5 5 2 5 3 2 1 5 0 5 3 5 3 4 3 5 5 5 5 2 4 5 5
 4 5 5 5 2 4 5 5 5 5 1 5 5 4 0 3 3 4 2 3 1 1 5 5 4 4 4 4 5 2 5 4 3 3 4 5 5
 2 4 3 4 5 4 2 4 5 4 5 5 1 5 5 5 5 2 2 5 3 5 4 5 4 4 5 5 4 2 2 4 3 3 5 4 2
 2 2 2 5 5 4 5 3 4 4 3 4 4 2 2 5 2 2 2 2 5 0 3 4 5 1 4 1 4 5 4 5 5 3 4 5 4
 3 5 1 2 4 5 5 5 5 3 5 1 4 5 5 2 5 4 3 2 2 2 2 3 5 3 3 5 3 5 3 4 2 4 4 5 2
 5 5 5 1 4 5 5 5 4 5 2 5 2 1 5 5 4 1 1 4 4 4 4 2 5 5 4 2 5 5 5 1 5 4 2 5 5
 4 5 4 4 5 5 5 4 5 0 2 2 4 2 4 5 4 5 1 5 2 5 3 5 5 3 5 5 2 5 3 4 5 2 2 5 5
 4 5 4 4 4 5 2 4 5 2 5 0 

In [94]:
print(len(X_input)) #OR len(X_input) ---same thing

500


In [95]:
len(X_input)

500

In [96]:
len(Y_target)

500

In [97]:
#Split the data in X_train, Y_train and X_test, Y_test

X_train = X_input[:400]
X_test = X_input[400:]
Y_train = Y_target[:400]
Y_test = Y_target[400:]

In [98]:
#samples in train and test

print(f"sample in X_train {len(X_train)}, Sample in X_test {len(X_test)}")

sample in X_train 400, Sample in X_test 100


In [99]:
print(f"Sample in Y_train {len(Y_train)}, Sample in Y_test {len(Y_test)}")

Sample in Y_train 400, Sample in Y_test 100


In [100]:
#Training libs
from sklearn.metrics import classification_report #for checking precision(not from class)
from sklearn.metrics import accuracy_score #to check accuracy

### Training

In [101]:
from sklearn.neighbors import KNeighborsClassifier

In [102]:
trainer = KNeighborsClassifier(n_neighbors=10)

In [103]:
lerner = trainer.fit(X_train,Y_train) #(Error Problem so mark as comment)

In [104]:
#Testing X_test......Y_test

Ya = Y_test
Yp = lerner.predict(X_test)

In [105]:
#Find some problem
Yp

array([3, 4, 2, 4, 4, 5, 2, 5, 5, 5, 1, 4, 5, 5, 5, 4, 5, 2, 5, 2, 1, 5, 5,
       4, 2, 1, 4, 4, 4, 4, 2, 5, 5, 4, 2, 5, 5, 5, 1, 5, 4, 2, 5, 5, 4, 5,
       4, 4, 5, 5, 5, 4, 5, 0, 2, 2, 4, 3, 4, 5, 4, 5, 1, 5, 2, 5, 3, 5, 5,
       3, 5, 5, 2, 4, 3, 4, 5, 2, 2, 5, 5, 4, 5, 4, 4, 4, 5, 2, 4, 5, 2, 5,
       0, 2, 5, 5, 4, 5, 5, 5], dtype=int64)

In [106]:
Ya

array([3, 4, 2, 4, 4, 5, 2, 5, 5, 5, 1, 4, 5, 5, 5, 4, 5, 2, 5, 2, 1, 5, 5,
       4, 1, 1, 4, 4, 4, 4, 2, 5, 5, 4, 2, 5, 5, 5, 1, 5, 4, 2, 5, 5, 4, 5,
       4, 4, 5, 5, 5, 4, 5, 0, 2, 2, 4, 2, 4, 5, 4, 5, 1, 5, 2, 5, 3, 5, 5,
       3, 5, 5, 2, 5, 3, 4, 5, 2, 2, 5, 5, 4, 5, 4, 4, 4, 5, 2, 4, 5, 2, 5,
       0, 1, 5, 5, 4, 5, 5, 5], dtype=int64)

# Great Job SHivan!