In [5]:
import numpy as pn
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [6]:
data = pd.read_csv(r"C:\ProgramData\Ml_Data\Housing_Data.csv")

In [7]:
data.head()

Unnamed: 0    price  lotsize  bedrooms  bathrms  stories driveway recroom  \
0           1  42000.0     5850         3        1        2      yes      no   
1           2  38500.0     4000         2        1        1      yes      no   
2           3  49500.0     3060         3        1        1      yes      no   
3           4  60500.0     6650         3        1        2      yes     yes   
4           5  61000.0     6360         2        1        1      yes      no   

  fullbase gashw airco  garagepl prefarea  
0      yes    no    no         1       no  
1       no    no    no         0       no  
2       no    no    no         0       no  
3       no    no    no         0       no  
4       no    no    no         0       no

In [8]:
data.tail()

Unnamed: 0     price  lotsize  bedrooms  bathrms  stories driveway  \
541         542   91500.0     4800         3        2        4      yes   
542         543   94000.0     6000         3        2        4      yes   
543         544  103000.0     6000         3        2        4      yes   
544         545  105000.0     6000         3        2        2      yes   
545         546  105000.0     6000         3        1        2      yes   

    recroom fullbase gashw airco  garagepl prefarea  
541     yes       no    no   yes         0       no  
542      no       no    no   yes         0       no  
543     yes       no    no   yes         1       no  
544     yes       no    no   yes         1       no  
545      no       no    no   yes         1       no

In [9]:
data.shape

(546, 13)

In [10]:
data.columns

Index(['Unnamed: 0', 'price', 'lotsize', 'bedrooms', 'bathrms', 'stories',
       'driveway', 'recroom', 'fullbase', 'gashw', 'airco', 'garagepl',
       'prefarea'],
      dtype='object')

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 546 entries, 0 to 545
Data columns (total 13 columns):
Unnamed: 0    546 non-null int64
price         546 non-null float64
lotsize       546 non-null int64
bedrooms      546 non-null int64
bathrms       546 non-null int64
stories       546 non-null int64
driveway      546 non-null object
recroom       546 non-null object
fullbase      546 non-null object
gashw         546 non-null object
airco         546 non-null object
garagepl      546 non-null int64
prefarea      546 non-null object
dtypes: float64(1), int64(6), object(6)
memory usage: 55.5+ KB


In [22]:
data.isnull().sum()

Unnamed: 0    0
price         0
lotsize       0
bedrooms      0
bathrms       0
stories       0
driveway      0
recroom       0
fullbase      0
gashw         0
airco         0
garagepl      0
prefarea      0
dtype: int64

In [126]:
import math

In [ ]:
# data.badroom.median()

In [ ]:
# data.badroom.fillna(data.badroom.median())

In [127]:
data.isnull().sum().plot(kind='bar')

In [129]:
x=data.iloc[:,[2,3,4]].values

In [130]:
x

array([[5850,    3,    1],
       [4000,    2,    1],
       [3060,    3,    1],
       ..., 
       [6000,    3,    2],
       [6000,    3,    2],
       [6000,    3,    1]], dtype=int64)

In [131]:
y = data['price'].values

In [133]:
y

array([  42000.,   38500.,   49500.,   60500.,   61000.,   66000.,
         66000.,   69000.,   83800.,   88500.,   90000.,   30500.,
         27000.,   36000.,   37000.,   37900.,   40500.,   40750.,
         45000.,   45000.,   48500.,   65900.,   37900.,   38000.,
         42000.,   42300.,   43500.,   44000.,   44500.,   44900.,
         45000.,   48000.,   49000.,   51500.,   61000.,   61000.,
         61700.,   67000.,   82000.,   54500.,   66500.,   70000.,
         82000.,   92000.,   38000.,   44000.,   41000.,   43000.,
         48000.,   54800.,   55000.,   57000.,   68000.,   95000.,
         38000.,   25000.,   25245.,   56000.,   35500.,   30000.,
         48000.,   48000.,   52000.,   54000.,   56000.,   60000.,
         60000.,   67000.,   47000.,   70000.,   45000.,   51000.,
         32500.,   34000.,   35000.,   36000.,   45000.,   47000.,
         55000.,   63900.,   50000.,   35000.,   50000.,   43000.,
         55500.,   57000.,   60000.,   78000.,   35000.,   440

In [134]:
from sklearn.model_selection import train_test_split

In [135]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.20,random_state=0)

In [136]:
xtrain

array([[4300,    3,    2],
       [7410,    3,    1],
       [6000,    3,    2],
       ..., 
       [5500,    3,    2],
       [6600,    3,    1],
       [3480,    3,    1]], dtype=int64)

In [137]:
xtest

array([[ 6480,     3,     1],
       [ 7800,     3,     2],
       [ 8250,     3,     1],
       [ 5495,     3,     1],
       [ 3760,     3,     1],
       [ 5170,     3,     1],
       [ 4320,     3,     1],
       [ 6060,     3,     1],
       [ 6720,     3,     1],
       [ 3660,     4,     1],
       [ 3000,     3,     1],
       [ 3600,     3,     1],
       [ 5040,     3,     1],
       [ 8880,     3,     2],
       [ 2550,     3,     1],
       [ 7155,     3,     2],
       [ 3960,     3,     1],
       [ 7440,     3,     2],
       [ 7700,     2,     1],
       [ 5450,     2,     1],
       [ 6420,     3,     1],
       [ 7500,     3,     3],
       [ 5948,     3,     1],
       [ 3960,     3,     1],
       [ 4700,     4,     1],
       [ 5500,     3,     1],
       [ 3630,     3,     2],
       [ 8100,     4,     1],
       [ 2910,     3,     1],
       [ 4500,     4,     2],
       [ 4815,     2,     1],
       [ 4995,     4,     2],
       [ 3640,     4,     1],
       [ 4

In [138]:
ytrain

array([ 106500.,   92500.,  103000.,   50000.,   62000.,   87000.,
         74900.,   50000.,  113000.,   75000.,  120000.,  133000.,
         90000.,   95500.,   92000.,   90000.,   80000.,   47000.,
         94000.,   60000.,   80000.,  117000.,   50000.,  105000.,
         87000.,   52000.,   89000.,   33000.,   69000.,   75000.,
         65000.,   58500.,   71000.,   60500.,   79000.,   59900.,
        140000.,   38000.,   45000.,   84900.,   54800.,   57000.,
         53500.,  175000.,   83000.,   85000.,   25245.,   57250.,
         48000.,   66000.,   83800.,   86900.,   55000.,   83900.,
         49000.,   60000.,   82000.,   50000.,  145000.,   62500.,
         64000.,   34000.,   60000.,   49000.,   70000.,   48000.,
        105000.,   30000.,   53900.,   54000.,   53000.,   91500.,
         42500.,   42000.,   68000.,   25000.,   32000.,   32500.,
         60000.,   62000.,   78900.,   61000.,  120000.,   45000.,
         75000.,   42000.,  108000.,   68000.,   35000.,   435

In [139]:
ytest

array([  57000.,  132000.,   53900.,   44700.,   65000.,   67000.,
         67000.,   47000.,   70000.,   42000.,   56000.,   58550.,
         60000.,   99000.,   65000.,  124000.,   40000.,  106000.,
         35000.,   52900.,   87500.,  155000.,   70500.,   57000.,
         80000.,   83900.,   57500.,  141000.,   25000.,   51000.,
         69000.,   69900.,   46200.,  118500.,   75000.,   70800.,
         70000.,   27000.,   37900.,   60000.,  103500.,   45000.,
         40750.,   59500.,   85000.,   75000.,   86000.,   44000.,
         70000.,   99000.,   79500.,   54000.,   87000.,   71500.,
         62600.,   49000.,   65000.,   45000.,   73000.,   85000.,
         87250.,   60000.,   73000.,   44000.,   76000.,   41000.,
        125000.,   30000.,   65900.,   58500.,   78000.,   72000.,
        132000.,   51000.,   36000.,   75000.,   55000.,   84000.,
         95000.,   57000.,   97000.,   93000.,   57500.,   67000.,
         43000.,   89500.,   64500.,   83000.,  112500.,   685

In [140]:
linear = LinearRegression()

In [141]:
linear.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [142]:
pred_y = linear.predict(xtest)

In [143]:
xtest[3]

array([5495,    3,    1], dtype=int64)

In [144]:
pred_y[3]

64546.871187491983

In [147]:
# from sklearn.metrics import mean_squared_error
# predictions = linear.predict(xtest)
# lin_mse = mean_squared_error(ytest,predictions)
# lin_rmse = np.sqrt(lin_mse)
# print('rmse value is : ',lin_rmse)

In [148]:
# lin_reg_score = linear.score(xtest,ytest)
# print('r squared value is : ',lin_reg_score )

In [108]:
# plt.scatter(xtest,ytrain,color='green')
# plt.plot(xtrain,linear.predict(xtrain),color='blue')
# plt.title("Salary & Exp traing plot.")
# plt.xlabel("Exp")
# plt.ylabel("Salary")
# plt.show()