In [77]:
import numpy as np

In [78]:
import pandas as pd

In [79]:
import matplotlib.pyplot as plt

In [80]:
data = pd.read_csv(r"C:\ProgramData\Ml_Data\canada_per_capita_income.csv")

In [81]:
data.head()

year  per capita income (US$)
0  1970              3399.299037
1  1971              3768.297935
2  1972              4251.175484
3  1973              4804.463248
4  1974              5576.514583

In [82]:
data.shape

(47, 2)

In [84]:
real_x = data.iloc[:,0:1].values
real_y = data.iloc[:,1].values

In [85]:
# %matplotlib.inline
# plt.xlabel('year')
# plt.ylabel('Per capita income')
# plt.scatter(real_x,data.real_y)
# plt.show()

In [86]:
# real_x
# real_y

In [87]:
from sklearn.model_selection import train_test_split

In [88]:
xtrain,ytrain,xtest,ytest = train_test_split(real_x,real_y, test_size=.30,random_state=0)

In [89]:
from sklearn.linear_model import LinearRegression

In [90]:
lin = LinearRegression()

In [91]:
lin.fit(real_x,real_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [92]:
pred_y = lin.predict(real_x)

In [96]:
# ytest[3]

In [97]:
# pred_y[3]

In [98]:
lin.predict([[2020]])

array([ 41288.69409442])

In [100]:
lin.predict([[1973]])

array([ 2350.83555895])

# Mathematically

In [101]:
lin.coef_

array([ 828.46507522])

In [102]:
lin.intercept_

-1632210.7578554575

In [104]:
# y = m*x+b
828.46507522*2020+-1632210.7578554575

41288.694088942604